apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aigctp
  labels:
    app.kubernetes.io/name: aigctp
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/component: backend
