"""add_composite_indexes

Revision ID: 305b2b6167ed
Revises: 7489b69bca52
Create Date: 2026-05-04 20:56:24.234357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305b2b6167ed'
down_revision: Union[str, None] = '7489b69bca52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index('ix_conversations_session_user', 'conversations', ['session_id', 'user_id'], unique=False)
    op.create_index('ix_meal_records_user_date', 'meal_records', ['user_id', 'date'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index('ix_meal_records_user_date', table_name='meal_records')
    op.drop_index('ix_conversations_session_user', table_name='conversations')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    # ### end Alembic commands ###
